permit:
  pdpUrl: 'http://171.254.94.32:7766'
  apiUrl: 'http://171.254.94.32:8000'
  apiKey: vauthz_66d4effcc1a747be8f37bda823ac45d3
springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true